### ISSUE TITLE
extension doesn't work

### ISSUE THREAD

**Issue by tjx666** [DennisvHest/vscode-npm-browser#18]
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

![Snipaste_2020-07-07_11-56-48](https://user-images.githubusercontent.com/41773861/86705940-f6433780-c048-11ea-892e-529361270b60.png)

**Comment by DennisvHest** [comment]
Thanks for the bug report. I have a feeling it is unable to read the file because of the backslashes in the file path on Mac. I will look into this.

**Comment by DennisvHest** [comment]
I was able to reproduce the error in a MacOS VM. I have fixed the issue and published a new release. Could you confirm that the extension works now?

**Comment by tjx666** [comment]
@DennisvHest  Latest version works great。
<img width="1280" alt="Snipaste_2020-07-11_23-10-25" src="https://user-images.githubusercontent.com/41773861/87227200-f6865e80-c3cb-11ea-90e5-6c8100246a8a.png">
