### ISSUE TITLE
Updating devDeps should automatically use --save-dev

### ISSUE THREAD

**Issue by SrBrahma** [DennisvHest/vscode-npm-browser#21]
Currently, when updating a development dependency, the --save-prod is used as default argument, as seen in the "More installation options". The default argument of when updating a package should follow the current package dependency type (prod or dev)

**Comment by DennisvHest** [comment]
Hey @SrBrahma, thanks for creating this issue. I will implement this when I have time to work on this in early october.

**Comment by DennisvHest** [comment]
Hey @SrBrahma, this functionality has been added in the [1.0.4](https://github.com/DennisvHest/vscode-npm-browser/releases/tag/1.0.4) release.
