### ISSUE TITLE
How do you fetch the NPM Packages?

### ISSUE THREAD

**Issue by max-programming** [DennisvHest/vscode-npm-browser#24]
## Just a Question
I couldn't find any way to contact you. And I wanted to know how did you fetch the NPM Packages. Can you please tell me how you did it? I looked into the source code but I couldn't find it

**Comment by DennisvHest** [comment]
Hi @max-programming, the packages are fetched from the [NPM Registry API](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md). In the NPM browser the requests also go through a proxy server to avoid CORS. I am planning to possibly change this to fetching the packages by executing the `npm view` and `npm search` commands in the NPM cli (#22).

**Comment by max-programming** [comment]
Thanks a lot for the information Dennis. Your extension is really nice.
