### ISSUE TITLE
package.json not found, but does exist in workspace

### ISSUE THREAD

**Issue by sauntimo** [DennisvHest/vscode-npm-browser#27]
## Questions
- Can I point the extension at the package.json manually?
- Is there a reason why it's failing to find it in the root of the only folder in the workspace?
- Sorry if these answers to these questions exist in the docs and I've missed them - I did have a look!

## Specs
- Mac OS 11 Big Sur
- VSCode 1.52.1 Nov 2020
- NPM browser 1.1.0

## Screenshot
<img width="1680" alt="Screenshot 2021-02-03 at 09 56 40" src="https://user-images.githubusercontent.com/2720466/106730098-1e5a3f80-6606-11eb-93dc-84f502c092e9.png">

**Comment by DennisvHest** [comment]
@sauntimo, thanks for creating this issue. It is not possible to manually point to a package.json file. The extension should be able to find the package.json in the root of the workspace. The extension basically looks for any package.json files in the workspace that are not in a node_modules folder. Another reason it would be unable to "find" the package.json could be that it had a problem reading the package.json itself, but I doubt that that's the case.

Do you have this problem with this workspace specifically or does it also occur in other workspaces with a package.json? If there is any error that occurs, you should be able to see it in the devtools window when the extension is open. You can do this by pressing CMD+SHIFT+F12 and opening "developer tools" or "webview developer tools" while te extension is open.

![image](https://user-images.githubusercontent.com/18610083/107064122-75fdd400-67db-11eb-9872-f9110310ee89.png)

If there are any errors, i could look into the cause of this problem.

**Comment by sauntimo** [comment]
Hey @DennisvHest thanks for getting back to me. Having just seen your comment, I reenabled the extension and it's working fine! I note that this morning my VSCode updated to 1.53.0, so I wonder if that fixed something? Anyway, if it misbehaves again, I'll see if I can grab the error and share it with you.

Also, neat idea for a useful extension, I'll enjoy using it!

**Comment by DennisvHest** [comment]
That's good to hear! Thanks!
