### ISSUE TITLE
[BUG] Broken in multi-package.json project. Not showing any deps

### ISSUE THREAD

**Issue by romgerman** [DennisvHest/vscode-npm-browser#28]
Hello. Good idea with the extension! However there is some problems I've encountered.

My project has multiple package.json files. After installing it and opening the sidebar it asked me which package.json I want to use now. I've selected my main package.json (in root folder) and then nothing happened. No deps showed up in the sidebar
![image](https://user-images.githubusercontent.com/1517367/149109480-8f66cabb-2c54-4379-a335-4d8fae000edf.png)

And when I closed the browser view and opened the extension sidebar again the browser view started showing up some text (I guessed it's from the first package.json in the project (it's not in the root folder but higher in explorer sidebar) cordova-plugin-qrscanner).
![image](https://user-images.githubusercontent.com/1517367/149112924-04b811f8-3c39-4d0b-bfb0-b9ee14b1d869.png)

**Comment by DennisvHest** [comment]
Hey @romgerman, thanks for the bug report.

I was able to reproduce the issue with the dependencies not loading. This seems to happen on first use in a new workspace.
I have created a new release ([1.1.1](https://github.com/DennisvHest/vscode-npm-browser/releases/tag/1.1.1)) that fixes this. VSCode should automatically update the extension to the new version.

I was not able to reproduce the issue of the package.json text in the browser view. Though I have seen this issue very rarely myself before. Restarting VSCode always made the issue dissapear.

If you are still experience any issue, please let me know.
